---
- hosts: 172.31.14.175
  become: yes
  tasks:
  - name: install git
    apt:
       name: git
       state: present

  - name: install tree
    apt:
       name: tree
       state: present

  - name: installllll wget
    apt:
      name: wget
      state: present 

      