---
# tasks file for mywebrole
- name: install webserver
  apt:
    name: apache2
    state: present
- name: copy indexfile
  template:
      src: templates/myidenx.j2
      dest: /var/www/html/index.html
  notify: restartedwebserver
    